baseURL = "https://coldsteam-studio.github.io/eyes-of-wadzi/"
languageCode = "en-us"
title = "Eyes of Wadzi"

[taxonomies]
    category = "categories"

[caches]
    [caches.images]
        dir    = ":cacheDir/galleriesdeluxe"
        maxAge = "4320h"

[params]
    [params.galleriesdeluxe]
        sass_transpiler = "dartsass"

[params.gallerydeluxe]
    shuffle     = false
    reverse     = true
    enable_exif = false

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"
